### ISSUE TITLE
Missing 2020.2.0f1

### ISSUE THREAD

**Issue by marwie** [Larusso/unity-versions-service#28]
2020.0f1 is missing from https://github.com/Larusso/unity-versions-service/blob/master/versions.yml

https://unity3d.com/de/unity/whats-new/2020.2.0

**Comment by Larusso** [comment]
Missing version added and service deployed
https://github.com/Larusso/unity-versions-service/commit/01f46c70900fedc655bf8344057d2ee1037d88f6
