### ISSUE TITLE
Changeset for 2020.1.0a20

### ISSUE THREAD

**Issue by marwie** [Larusso/unity-versions-service#4]
Nice project

Looking at the yaml there seems to be an error for 2020.1.0a20:

`2020.1.0a20: "019325219793"`

https://raw.githubusercontent.com/Larusso/unity-versions-service/master/versions.yml

**Comment by Larusso** [comment]
Thanks for reporting this. Will take a look.

**Comment by Larusso** [comment]
Hmm.
The changeset is correct. Check this download url for example: https://beta.unity3d.com/download/019325219793/Windows64EditorInstaller/UnitySetup64.exe

Or what is the error?

**Comment by marwie** [comment]
Ah sorry for the bad description. I was just referring to some changesets being in quotes

**Comment by Larusso** [comment]
That is `yml`. The serializer uses by default the shortest value without operators possible. But if the value consists only of numbers the deserializer doesn't know what it should be. So quotes are optional to enforce a string.
