### ISSUE TITLE
Missing versions 2021.1.0a7 to 2021.1.0a9

### ISSUE THREAD

**Issue by marwie** [Larusso/unity-versions-service#5]
Hi,
we just noticed that versions from 2021.1.0a7 to 2021.1.0a9 seem to be missing 

https://unity3d.com/de/unity/alpha/2021.1.0a6
...
https://unity3d.com/de/unity/alpha/2021.1.0a8
https://unity3d.com/de/unity/alpha/2021.1.0a9

**Comment by Larusso** [comment]
Hi thanks for the issue.
This repo is in full automation mode and during december something broke. I added the missing versions now and fixed the issue with the autoupdater.

**Comment by marwie** [comment]
Thank you!
